# ~/.config/sunshine/sunshine.conf
# Capture the virtual display. Replace /home/USER with your home directory.
output_name = HDMI-A-1
global_prep_cmd = [{"do":"/home/USER/.local/share/sunshine-virtual-display/stream-start.sh","undo":"/home/USER/.local/share/sunshine-virtual-display/stream-stop.sh"}]
